//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHAY.DATA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceKendoUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceKendoUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PHAY.DATA.Resources.ResourceKendoUI", typeof(ResourceKendoUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đậm.
        /// </summary>
        internal static string Editor_Bold {
            get {
                return ResourceManager.GetString("Editor_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn liên kết.
        /// </summary>
        internal static string Editor_CreateLink {
            get {
                return ResourceManager.GetString("Editor_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn font.
        /// </summary>
        internal static string Editor_FontName {
            get {
                return ResourceManager.GetString("Editor_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (kế thừa font).
        /// </summary>
        internal static string Editor_FontNameInherit {
            get {
                return ResourceManager.GetString("Editor_FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn kích thước chữ.
        /// </summary>
        internal static string Editor_FontSize {
            get {
                return ResourceManager.GetString("Editor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (kế thừa kích thước).
        /// </summary>
        internal static string Editor_FontSizeInherit {
            get {
                return ResourceManager.GetString("Editor_FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng.
        /// </summary>
        internal static string Editor_FormatBlock {
            get {
                return ResourceManager.GetString("Editor_FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thụt vào.
        /// </summary>
        internal static string Editor_Indent {
            get {
                return ResourceManager.GetString("Editor_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn HTML.
        /// </summary>
        internal static string Editor_InsertHtml {
            get {
                return ResourceManager.GetString("Editor_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn hình ảnh.
        /// </summary>
        internal static string Editor_InsertImage {
            get {
                return ResourceManager.GetString("Editor_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn danh sách thứ tự.
        /// </summary>
        internal static string Editor_InsertOrderedList {
            get {
                return ResourceManager.GetString("Editor_InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèn danh sách không thứ tự.
        /// </summary>
        internal static string Editor_InsertUnorderedList {
            get {
                return ResourceManager.GetString("Editor_InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiêng.
        /// </summary>
        internal static string Editor_Italic {
            get {
                return ResourceManager.GetString("Editor_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canh giữa.
        /// </summary>
        internal static string Editor_JustifyCenter {
            get {
                return ResourceManager.GetString("Editor_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canh đều.
        /// </summary>
        internal static string Editor_JustifyFull {
            get {
                return ResourceManager.GetString("Editor_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canh trái.
        /// </summary>
        internal static string Editor_JustifyLeft {
            get {
                return ResourceManager.GetString("Editor_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canh phải.
        /// </summary>
        internal static string Editor_JustifyRight {
            get {
                return ResourceManager.GetString("Editor_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thụt ra.
        /// </summary>
        internal static string Editor_Outdent {
            get {
                return ResourceManager.GetString("Editor_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gạch ngang.
        /// </summary>
        internal static string Editor_Strikethrough {
            get {
                return ResourceManager.GetString("Editor_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu.
        /// </summary>
        internal static string Editor_Styles {
            get {
                return ResourceManager.GetString("Editor_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string Editor_Subscript {
            get {
                return ResourceManager.GetString("Editor_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string Editor_Superscript {
            get {
                return ResourceManager.GetString("Editor_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gạch chân.
        /// </summary>
        internal static string Editor_Underline {
            get {
                return ResourceManager.GetString("Editor_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa liên kết.
        /// </summary>
        internal static string Editor_Unlink {
            get {
                return ResourceManager.GetString("Editor_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Và.
        /// </summary>
        internal static string Filter_And {
            get {
                return ResourceManager.GetString("Filter_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa sạch.
        /// </summary>
        internal static string Filter_Clear {
            get {
                return ResourceManager.GetString("Filter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng với.
        /// </summary>
        internal static string Filter_DateIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớn hơn.
        /// </summary>
        internal static string Filter_DateIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớn hơn hoặc bằng.
        /// </summary>
        internal static string Filter_DateIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỏ hơn.
        /// </summary>
        internal static string Filter_DateIsLessThan {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỏ hơn hoặc bằng.
        /// </summary>
        internal static string Filter_DateIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không bằng.
        /// </summary>
        internal static string Filter_DateIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_DateIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng.
        /// </summary>
        internal static string Filter_EnumIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không bằng.
        /// </summary>
        internal static string Filter_EnumIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_EnumIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        internal static string Filter_Filter {
            get {
                return ResourceManager.GetString("Filter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị dữ liệu với điều kiện:.
        /// </summary>
        internal static string Filter_Info {
            get {
                return ResourceManager.GetString("Filter_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sai.
        /// </summary>
        internal static string Filter_IsFalse {
            get {
                return ResourceManager.GetString("Filter_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đúng.
        /// </summary>
        internal static string Filter_IsTrue {
            get {
                return ResourceManager.GetString("Filter_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng.
        /// </summary>
        internal static string Filter_NumberIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớn hơn.
        /// </summary>
        internal static string Filter_NumberIsGreaterThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớn hơn hoặc bằng.
        /// </summary>
        internal static string Filter_NumberIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỏ hơn.
        /// </summary>
        internal static string Filter_NumberIsLessThan {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỏ hơn hoặc bằng.
        /// </summary>
        internal static string Filter_NumberIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không bằng.
        /// </summary>
        internal static string Filter_NumberIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_NumberIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoặc.
        /// </summary>
        internal static string Filter_Or {
            get {
                return ResourceManager.GetString("Filter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chọn giá trị -.
        /// </summary>
        internal static string Filter_SelectValue {
            get {
                return ResourceManager.GetString("Filter_SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứa.
        /// </summary>
        internal static string Filter_StringContains {
            get {
                return ResourceManager.GetString("Filter_StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không chứa.
        /// </summary>
        internal static string Filter_StringDoesNotContain {
            get {
                return ResourceManager.GetString("Filter_StringDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc bằng.
        /// </summary>
        internal static string Filter_StringEndsWith {
            get {
                return ResourceManager.GetString("Filter_StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng.
        /// </summary>
        internal static string Filter_StringIsEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không bằng.
        /// </summary>
        internal static string Filter_StringIsNotEqualTo {
            get {
                return ResourceManager.GetString("Filter_StringIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu bằng.
        /// </summary>
        internal static string Filter_StringStartsWith {
            get {
                return ResourceManager.GetString("Filter_StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Grid_Cancel {
            get {
                return ResourceManager.GetString("Grid_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy thay đổi.
        /// </summary>
        internal static string Grid_CancelChanges {
            get {
                return ResourceManager.GetString("Grid_CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cột.
        /// </summary>
        internal static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dòng dữ liệu được chọn?.
        /// </summary>
        internal static string Grid_Confirmation {
            get {
                return ResourceManager.GetString("Grid_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string Grid_Create {
            get {
                return ResourceManager.GetString("Grid_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Grid_Destroy {
            get {
                return ResourceManager.GetString("Grid_Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu cập nhật.
        /// </summary>
        internal static string Grid_SaveChanges {
            get {
                return ResourceManager.GetString("Grid_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Grid_Select {
            get {
                return ResourceManager.GetString("Grid_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp tăng dần.
        /// </summary>
        internal static string Grid_SortAscending {
            get {
                return ResourceManager.GetString("Grid_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp giảm dần.
        /// </summary>
        internal static string Grid_SortDescending {
            get {
                return ResourceManager.GetString("Grid_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string Grid_Update {
            get {
                return ResourceManager.GetString("Grid_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kéo và thả một tiêu đề cột vào đây để nhóm dữ liệu.
        /// </summary>
        internal static string Group_Empty {
            get {
                return ResourceManager.GetString("Group_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} của {2}.
        /// </summary>
        internal static string Pager_Display {
            get {
                return ResourceManager.GetString("Pager_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu để hiển thị.
        /// </summary>
        internal static string Pager_Empty {
            get {
                return ResourceManager.GetString("Pager_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đầu tiên.
        /// </summary>
        internal static string Pager_First {
            get {
                return ResourceManager.GetString("Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mẫu tin/trang.
        /// </summary>
        internal static string Pager_ItemsPerPage {
            get {
                return ResourceManager.GetString("Pager_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cuối cùng.
        /// </summary>
        internal static string Pager_Last {
            get {
                return ResourceManager.GetString("Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang tiếp theo.
        /// </summary>
        internal static string Pager_Next {
            get {
                return ResourceManager.GetString("Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trên {0}.
        /// </summary>
        internal static string Pager_Of {
            get {
                return ResourceManager.GetString("Pager_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string Pager_Page {
            get {
                return ResourceManager.GetString("Pager_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang trước.
        /// </summary>
        internal static string Pager_Previous {
            get {
                return ResourceManager.GetString("Pager_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        internal static string Pager_Refresh {
            get {
                return ResourceManager.GetString("Pager_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Upload_Cancel {
            get {
                return ResourceManager.GetString("Upload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kéo thả tệp vào đây để tải lên.
        /// </summary>
        internal static string Upload_DropFilesHere {
            get {
                return ResourceManager.GetString("Upload_DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Upload_Remove {
            get {
                return ResourceManager.GetString("Upload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử lại.
        /// </summary>
        internal static string Upload_Retry {
            get {
                return ResourceManager.GetString("Upload_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn....
        /// </summary>
        internal static string Upload_Select {
            get {
                return ResourceManager.GetString("Upload_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thất bại.
        /// </summary>
        internal static string Upload_StatusFailed {
            get {
                return ResourceManager.GetString("Upload_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã tải lên.
        /// </summary>
        internal static string Upload_StatusUploaded {
            get {
                return ResourceManager.GetString("Upload_StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đang tải lên.
        /// </summary>
        internal static string Upload_StatusUploading {
            get {
                return ResourceManager.GetString("Upload_StatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải tiệp lên.
        /// </summary>
        internal static string Upload_UploadSelectedFiles {
            get {
                return ResourceManager.GetString("Upload_UploadSelectedFiles", resourceCulture);
            }
        }
    }
}
