//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHAY.DATA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACL_Action
    {
        public int ID { get; set; }
        public int IDManHinh { get; set; }
        public string TenAction { get; set; }
        public string TenController { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Loai { get; set; }
        public string Ten { get; set; }
    }
}
