//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHAY.DATA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACL_NhomNguoiDung
    {
        public int ID { get; set; }
        public Nullable<int> IDThamChieu { get; set; }
        public string HoDem { get; set; }
        public string Ten { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string SoDiDong { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> IsRoot { get; set; }
        public Nullable<bool> IsNhom { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LoaiDoiTuong { get; set; }
        public Nullable<int> IDMapDoiTuong { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<int> IDNguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> IDNguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> IDNguoiDelete { get; set; }
        public Nullable<System.DateTime> NgayDelete { get; set; }
        public Nullable<int> IDHinhDaiDien { get; set; }
        public string MaXacThuc { get; set; }
        public Nullable<System.DateTime> NgayTaoMaXacThuc { get; set; }
        public Nullable<System.DateTime> NgayHetHanMaXacThuc { get; set; }
        public Nullable<int> SoThuTu { get; set; }
    }
}
