//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHAY.DATA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACL_PhanQuyen
    {
        public int ID { get; set; }
        public int IDAction { get; set; }
        public int IDNhomNguoiDung { get; set; }
        public Nullable<bool> IsChoPhep { get; set; }
        public Nullable<int> IDNguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> IDNguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
