//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHAY.DATA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HTWEntities : DbContext
    {
        public const string ConnectionStringDefault = "name=HTWEntities";
        public const string ContainerName = "HTWEntities";
        public const string MetaData = "metadata=res://*/Models.HTWModel.csdl|res://*/Models.HTWModel.ssdl|res://*/Models.HTWModel.msl;provider=System.Data.SqlClient;provider connection string=\"{0}\"";
        //public HTWEntities()
        //    : base("name=HTWEntities")
        //{
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACL_Action> ACL_Action { get; set; }
        public virtual DbSet<ACL_CauHinhManHinh> ACL_CauHinhManHinh { get; set; }
        public virtual DbSet<ACL_ManHinh> ACL_ManHinh { get; set; }
        public virtual DbSet<ACL_NhomNguoiDung> ACL_NhomNguoiDung { get; set; }
        public virtual DbSet<ACL_PhanQuyen> ACL_PhanQuyen { get; set; }
        public virtual DbSet<ACL_TaiKhoan> ACL_TaiKhoan { get; set; }
    
        public virtual ObjectResult<SP_ACL_QuyenNhom_Result> SP_ACL_QuyenNhom(Nullable<int> iDNhomManHinh, Nullable<int> iDUser)
        {
            var iDNhomManHinhParameter = iDNhomManHinh.HasValue ?
                new ObjectParameter("IDNhomManHinh", iDNhomManHinh) :
                new ObjectParameter("IDNhomManHinh", typeof(int));
    
            var iDUserParameter = iDUser.HasValue ?
                new ObjectParameter("IDUser", iDUser) :
                new ObjectParameter("IDUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACL_QuyenNhom_Result>("SP_ACL_QuyenNhom", iDNhomManHinhParameter, iDUserParameter);
        }
        public static string ConnectionString
        {
            get;
            set;
        }

        public HTWEntities()
            //: base("name=HTWEntities")
    		: base(string.IsNullOrEmpty(ConnectionString) ? ConnectionStringDefault : string.Format(MetaData, ConnectionString))
        {
        }
    
    	public HTWEntities(string connectionString)
                : base(string.IsNullOrEmpty(connectionString) ? ConnectionStringDefault : string.Format(MetaData, connectionString))
            {
            }
    }
}
